### ISSUE TITLE
Abstract the diagnostics printed in onAttach() into an exported function

### ISSUE THREAD

**Issue by jennybc** [r-lib/credentials#6]
usethis has a `git_sitrep()` function that reveals a lot about a user's Git setup, for diagnostic and troubleshooting purposes. In the past, this revealed info re: the git2r outlook.

Since usethis is shifting away from git2r in favour of gert + credentials, I want to reveal similar info. `gert::libgit2_config()` covers gert pretty well.

I'd like to include similar info from credentials.

Can we take the smarts in `.onAttach()` and move them into an actual exported function that other packages can call?

https://github.com/r-lib/credentials/blob/master/R/onattach.R

I'd love to get my hands on some of this info programmatically:

```
> library(credentials)
Found git version 2.24.3 (Apple Git-128)
Supported HTTPS credential helpers: cache, store
Found OpenSSH_8.1p1, LibreSSL 2.7.3
Default SSH key: /Users/jenny/.ssh/id_rsa
```

**Comment by jennybc** [comment]
As I get closer to a usethis release, I'm wondering if this could possibly happen before that. Are there other reasons to do a small credentials release soon-ish? Or maybe we could do (some of) it in gitcreds for now, which has to have its initial CRAN release anyway.

cc @gaborcsardi

**Comment by jeroen** [comment]
Yes we can factor it into a function, only the various verbose messages that you see in case things are not working may not be easy to export programmatically.

**Comment by jennybc** [comment]
I was discussing usethis v2.0.0 with Hadley today and he thinks `usethis::git_sitrep()` should surface *less* gert info than it currently does. Historically, we started doing this as a coping strategy for git2r and its long-standing problems with protocol support and credential-finding. But because this appears to work more smoothly with credentials + gert, we figure we can reveal less.

So I no longer want this for usethis reasons.

I'll leave the issue open @jeroen in case you want to do it anyway? But feel free to close.

And it's still possible that gitcreds should offer some of the same transparency (?).

**Comment by jeroen** [comment]
OK in that case I'll close it because I don't think anyone else will be interested in this level of detail. Lmk if you need anything else to unblock usethis 2.0
